---
- name: restart shadowsocks-rust
  systemd:
    name: "shadowsocks-rust-{{ item.item.type | default('server') }}@{{ item.item.name }}"
    state: restarted
  when: item.changed
  loop: "{{ create_config_results.results }}"
